name: login_page_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter_timer_countdown: ^1.0.5
  lottie: ^2.6.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/js.jpg
    - assets/images/java.jpg
    - assets/images/ml.jpg
    - assets/images/python.jpg
    - assets/images/sql.jpg
    - assets/images/flutter.jpg
    - assets/images/docker.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf